# Generated by Django 3.1.7 on 2021-03-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210310_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank_percentage',
            field=models.IntegerField(blank=True, default=15, verbose_name='Percents rank'),
        ),
    ]
