# Generated by Django 3.1.7 on 2021-03-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210310_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(blank=True, default='default-user-image.png', null=True, upload_to='', verbose_name='Image'),
        ),
    ]
