# Generated by Django 3.1.7 on 2021-03-09 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210227_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fast_start', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='username'),
        ),
        migrations.CreateModel(
            name='RecipeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='name')),
                ('time', models.CharField(max_length=50, null=True, verbose_name='time')),
                ('adderOf', models.CharField(max_length=100, null=True, verbose_name='adderOf')),
                ('category', models.CharField(choices=[('Горячие блюда', 'Горячие блюда'), ('Бульоны и супы', 'Бульоны и супы'), ('Салаты', 'Салаты'), ('Закуски', 'Закуски'), ('Выпечка', 'Выпечка'), ('Десерты', 'Десерты'), ('Соусы', 'Соусы')], max_length=200, null=True, verbose_name='category')),
                ('hardnessCook', models.CharField(choices=[('Очень легко', 'Очень легко'), ('Легко', 'Легко'), ('Средняя сложность', 'Средняя сложность'), ('Нужен опыт', 'Нужен опыт'), ('Сложно', 'Сложно'), ('Очень сложно', 'Очень сложно')], max_length=200, null=True, verbose_name='hardness')),
                ('ingredient1', models.CharField(blank=True, max_length=200, null=True, verbose_name='ingredients1')),
                ('ingredient2', models.CharField(blank=True, max_length=200, null=True, verbose_name='ingredients2')),
                ('ingredient3', models.CharField(blank=True, max_length=200, null=True, verbose_name='ingredients3')),
                ('ingredient4', models.CharField(blank=True, max_length=200, null=True, verbose_name='ingredients4')),
                ('ingredient5', models.CharField(blank=True, max_length=200, null=True, verbose_name='ingredients5')),
                ('ingredient6', models.CharField(blank=True, max_length=200, null=True, verbose_name='ingredients6')),
                ('ingredient7', models.CharField(blank=True, max_length=200, null=True, verbose_name='ingredients7')),
                ('ingredient8', models.CharField(blank=True, max_length=200, null=True, verbose_name='ingredients8')),
                ('ingredient9', models.CharField(blank=True, max_length=200, null=True, verbose_name='ingredients9')),
                ('ingredient10', models.CharField(blank=True, max_length=200, null=True, verbose_name='ingredients10')),
                ('mas1', models.CharField(blank=True, max_length=100, null=True, verbose_name='mas1')),
                ('mas2', models.CharField(blank=True, max_length=100, null=True, verbose_name='mas2')),
                ('mas3', models.CharField(blank=True, max_length=100, null=True, verbose_name='mas3')),
                ('mas4', models.CharField(blank=True, max_length=100, null=True, verbose_name='mas4')),
                ('mas5', models.CharField(blank=True, max_length=100, null=True, verbose_name='mas5')),
                ('mas6', models.CharField(blank=True, max_length=100, null=True, verbose_name='mas6')),
                ('mas7', models.CharField(blank=True, max_length=100, null=True, verbose_name='mas7')),
                ('mas8', models.CharField(blank=True, max_length=100, null=True, verbose_name='mas8')),
                ('mas9', models.CharField(blank=True, max_length=100, null=True, verbose_name='mas9')),
                ('mas10', models.CharField(blank=True, max_length=100, null=True, verbose_name='mas10')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_creat')),
                ('desc1', models.TextField(blank=True, null=True, verbose_name='desc1')),
                ('desc2', models.TextField(blank=True, null=True, verbose_name='desc2')),
                ('desc3', models.TextField(blank=True, null=True, verbose_name='desc3')),
                ('desc4', models.TextField(blank=True, null=True, verbose_name='desc4')),
                ('desc5', models.TextField(blank=True, null=True, verbose_name='desc5')),
                ('desc6', models.TextField(blank=True, null=True, verbose_name='desc6')),
                ('desc7', models.TextField(blank=True, null=True, verbose_name='desc7')),
                ('desc8', models.TextField(blank=True, null=True, verbose_name='desc8')),
                ('desc9', models.TextField(blank=True, null=True, verbose_name='desc9')),
                ('desc10', models.TextField(blank=True, null=True, verbose_name='desc10')),
                ('image1', models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image')),
                ('image2', models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image')),
                ('image3', models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image')),
                ('image4', models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image')),
                ('image5', models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image')),
                ('image6', models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image')),
                ('image7', models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image')),
                ('image8', models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image')),
                ('image9', models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image')),
                ('image10', models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image')),
                ('image_prod', models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image')),
                ('creator', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='achievements',
            field=models.ManyToManyField(to='main.Achievements'),
        ),
    ]
