# Generated by Django 3.1.7 on 2021-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210310_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, choices=[('Початківець', 'Початківець'), ('Професіонал', 'Професіонал')], default='Початківець', max_length=200, null=True, verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank_percentage',
            field=models.IntegerField(default=15, verbose_name='Percents rank'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Birthday'),
        ),
    ]
