# Generated by Django 3.1.7 on 2021-03-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customuser_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(blank=True, default='profile_ph.png', null=True, upload_to='', verbose_name='Image'),
        ),
    ]
