# Generated by Django 3.1.7 on 2021-03-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210310_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(blank=True, default='default_cook.png', null=True, upload_to='', verbose_name='Image'),
        ),
    ]
