# Generated by Django 3.1.7 on 2021-03-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_customuser_my_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeproduct',
            name='uuid_recipe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='uuid'),
        ),
    ]
