# Generated by Django 3.1.7 on 2021-03-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_recipeproduct_uuid_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_apple', models.BooleanField(blank=True, default=False)),
                ('q_apple', models.IntegerField(blank=True, default=0, verbose_name='Quantity of apples')),
                ('is_banana', models.BooleanField(blank=True, default=False)),
                ('q_banana', models.IntegerField(blank=True, default=0, verbose_name='Quantity of banana')),
            ],
        ),
    ]
