# Generated by Django 3.1.7 on 2021-04-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeproduct',
            name='emailof_creator',
            field=models.CharField(blank=True, max_length=100, verbose_name='email_creator'),
        ),
    ]
