# Generated by Django 3.1.7 on 2021-04-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_subscribtions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribtions',
            new_name='Subscribtion',
        ),
    ]
