# Generated by Django 3.1.7 on 2021-04-09 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_product'),
    ]

    operations = [
    ]
