# Generated by Django 3.1.7 on 2021-04-09 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='text_field',
        ),
        migrations.AddField(
            model_name='example',
            name='my_products',
            field=models.ManyToManyField(blank=True, to='main.RecipeProduct'),
        ),
        migrations.AddField(
            model_name='example',
            name='user2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
