# Generated by Django 3.1.7 on 2021-04-11 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210409_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Фрукти', 'Фрукти'), ('Овочі', 'Овочі'), ('Молочні продукти', 'Молочні продукти'), ("М'ясо", "М'ясо"), ('Риба', 'Риба'), ('Бакалія', 'Бакалія'), ('Консерви та приправи', 'Консерви та приправи'), ('Напої', 'Напої'), ('Заморожені продукти', 'Заморожені продукти')], max_length=30, null=True, verbose_name='Category')),
                ('nameUa', models.CharField(blank=True, max_length=50, verbose_name='UA')),
                ('quantity', models.FloatField(blank=True, default=0, verbose_name='Quantity')),
                ('measureUa', models.CharField(blank=True, choices=[('г', 'г'), ('шт', 'шт'), ('мл.', 'мл.'), ('кг.', 'кг.'), ('пуч.', 'пуч.'), ('бан.', 'бан.'), ('л.', 'л.'), ('упак.', 'упак.')], max_length=15, null=True, verbose_name='measure')),
                ('is_favorite', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
]
