# Generated by Django 3.1.7 on 2021-04-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210409_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=2)),
                ('name', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, to='main.AllInterests'),
        ),
    ]
