# Generated by Django 3.1.7 on 2021-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210415_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinterests',
            name='icon',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
