# Generated by Django 3.1.7 on 2021-04-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210416_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinterests',
            name='english',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
