# Generated by Django 3.1.7 on 2021-04-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_allinterests_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinterests',
            name='peopleSelected',
            field=models.IntegerField(blank=True, default=0, verbose_name='Users selected'),
        ),
    ]
