# Generated by Django 3.1.7 on 2021-04-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_delete_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alex_genius', models.CharField(blank=True, max_length=500, verbose_name='alex')),
            ],
        ),
    ]
