# Generated by Django 3.1.7 on 2021-04-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_storage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
