# Generated by Django 3.1.7 on 2021-04-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_delete_storage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_product',
        ),
    ]
