# Generated by Django 3.1.7 on 2021-04-16 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_delete_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleAlex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_products', models.ManyToManyField(blank=True, to='main.RecipeProduct')),
                ('user2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
