# Generated by Django 3.1.7 on 2021-04-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_user_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_products',
            field=models.ManyToManyField(blank=True, to='main.All_product'),
        ),
        migrations.AlterField(
            model_name='all_product',
            name='added_by',
            field=models.CharField(max_length=50, null=True, verbose_name='added_by'),
        ),
    ]
