# Generated by Django 3.1.7 on 2021-04-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210411_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_product',
            new_name='AllProduct',
        ),
        migrations.RenameModel(
            old_name='User_product_quantity',
            new_name='UserProductQuantity',
        ),
    ]
