# Generated by Django 3.1.7 on 2021-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210416_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplealex',
            name='my_products',
        ),
        migrations.AddField(
            model_name='examplealex',
            name='my_products',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
