# Generated by Django 3.1.7 on 2021-04-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210411_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproductquantity',
            old_name='owner',
            new_name='user',
        ),
    ]
