# Generated by Django 3.1.7 on 2021-04-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210416_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeproduct',
            name='adderOf',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='adderOf'),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('Горячие блюда', 'Горячие блюда'), ('Бульоны и супы', 'Бульоны и супы'), ('Салаты', 'Салаты'), ('Закуски', 'Закуски'), ('Выпечка', 'Выпечка'), ('Десерты', 'Десерты'), ('Соусы', 'Соусы')], max_length=200, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='hardnessCook',
            field=models.CharField(blank=True, choices=[('Очень легко', 'Очень легко'), ('Легко', 'Легко'), ('Средняя сложность', 'Средняя сложность'), ('Нужен опыт', 'Нужен опыт'), ('Сложно', 'Сложно'), ('Очень сложно', 'Очень сложно')], max_length=200, null=True, verbose_name='hardness'),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='time'),
        ),
        migrations.DeleteModel(
            name='Example',
        ),
    ]
