# Generated by Django 3.1.7 on 2021-04-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210416_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeproduct',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='my_recipes',
            field=models.ManyToManyField(blank=True, related_name='Recipes', to='main.RecipeProduct'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='recipeDraft',
        ),
        migrations.AddField(
            model_name='customuser',
            name='recipeDraft',
            field=models.ManyToManyField(blank=True, null=True, related_name='RecipeDraft', to='main.RecipeProduct'),
        ),
    ]
