# Generated by Django 3.1.7 on 2021-04-17 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210417_1433'),
    ]



    operations = [

      migrations.AddField(
            model_name='userproductquantity',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),

]

