# Generated by Django 3.2 on 2021-05-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210418_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='fast_start',
            new_name='is_gained',
        ),
        migrations.AddField(
            model_name='achievements',
            name='requirements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='rewardDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='rewardName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='rewardPoints',
            field=models.IntegerField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True, verbose_name='Бали'),
        ),
        migrations.AddField(
            model_name='achievements',
            name='rewardType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
