# Generated by Django 3.1.7 on 2021-04-17 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210417_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproduct',
            name='is_favorite',
        ),
	 migrations.CreateModel(
            name='ExampleAlex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_products', models.CharField(blank=True, max_length=200)),
                ('quantity1', models.FloatField(blank=True, default=0, verbose_name='Quantity')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),

]
