# Generated by Django 3.1.7 on 2021-05-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.recipeproduct'),
        ),
    ]
