# Generated by Django 3.2 on 2021-05-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210510_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='is_gained',
        ),
    ]
