# Generated by Django 3.1.7 on 2021-04-17 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210417_1459'),
    ]

    operations = [
	migrations.RemoveField(
            model_name='examplealex',
            name='quantity1',
        ),
	
    ]
