# Generated by Django 3.2 on 2021-05-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_achievements_is_gained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='rewardType',
            field=models.CharField(blank=True, choices=[('Профіль', 'profile'), ('Рецепти', 'recipes'), ('Соцільна активність', 'social_activity')], max_length=50, null=True),
        ),
    ]
