# Generated by Django 3.2 on 2021-05-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_achievements_rewardtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='rewardType',
            field=models.CharField(blank=True, choices=[('Профіль', 'Профіль'), ('Рецепти', 'Рецепти'), ('Соцільна активність', 'Соцільна активність')], max_length=50, null=True),
        ),
    ]
