# Generated by Django 3.1.7 on 2021-04-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_examplealex'),
    ]

    operations = [
    ]
