# Generated by Django 3.1.7 on 2021-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_examplealex_quantity1'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplealex',
            name='quantity1',
            field=models.FloatField(blank=True, default=0, verbose_name='Quantity'),
        ),
    ]
