# Generated by Django 3.2 on 2021-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_achievements_rewardtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='rewardPoints',
            field=models.IntegerField(blank=True, choices=[(2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Бали'),
        ),
    ]
