# Generated by Django 3.2 on 2021-05-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_achievements_rewardpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='icon',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='', verbose_name='Image'),
        ),
    ]
