# Generated by Django 3.1.7 on 2021-05-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_examplealex_quantity1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='main.AllProduct'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='my_products',
            field=models.ManyToManyField(blank=True, related_name='my_products', to='main.AllProduct'),
        ),
    ]
